language: cpp
compiler:
  - gcc
  - clang
before_script:
  - echo yes | sudo add-apt-repository ppa:marco89-7/root
  - sudo ./.raring-pinning.sh
  - sudo apt-get update -qq
  - sudo apt-get install -qq libc6-dev-i386 root-system libmysql++-dev libboost1.49-dev libboost-filesystem1.49-dev libboost-iostreams1.49-dev libboost-program-options1.49-dev libboost-regex1.49-dev libboost-system1.49 libboost-test1.49-dev
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
script:
  - make
  - make test
